export const OPEN_MODAL = 'OPEN_MODAL'
export const SET_CURRENT_US = 'SET_CURRENT_US'
export const SELECT_PAGE = 'SELECT_PAGE'
export const GET_ERRORS = 'GET_ERRORS'
export const REGISTER_USER = 'REGISTER_USER'